### ISSUE TITLE
only the first model extracted from the vml file

### ISSUE THREAD

**Issue by omyasuda** [chicortiz/.vml-to-.obj#8]
what to do with other data in the vml input file?

**Comment by chicortiz** [comment]
The ideia is to extract only vertices and faces to form the .obj and ignore
the rest for the time being.

Em ter., 10 de mai. de 2022 às 08:35, omyasuda ***@***.***>
escreveu:

**Comment by omyasuda** [comment]
ok... we can close this issue for now
